//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logger
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string ApiMethod { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string ApiUri { get; set; }
        public Nullable<bool> Success { get; set; }
        public string Reason { get; set; }
    }
}
